spring.application.name=SpringOauth2

spring.security.oauth2.client.registration.google.client-id= 72454325267-l35bcp5rusqckrcg2ajqcn6p39g54t4c.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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


#spring.security.oauth2.client.registration.github.client-id=
#spring.security.oauth2.client.registration.github.client-secret=